# Generated by Django 6.0 on 2026-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_training_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="training_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
