# Generated by Django 6.0 on 2026-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_training_training_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="training_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
