# Generated by Django 6.0 on 2026-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="reps",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="training",
            name="resistance_weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="training",
            name="sets",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
    ]
