# Generated by Django 6.0 on 2026-01-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_training_reps_training_resistance_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="text",
            field=models.CharField(max_length=200),
        ),
    ]
