# Generated by Django 6.0 on 2026-01-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_alter_training_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.IntegerField(default=1)),
                ("reps", models.IntegerField(default=1)),
                ("resistance_weight", models.FloatField(default=0.0)),
                ("comment", models.CharField(max_length=200)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.training",
                    ),
                ),
            ],
        ),
    ]
