# Generated by Django 6.0 on 2026-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="training",
            name="resistance_weight",
        ),
    ]
