# Generated by Django 6.0 on 2026-01-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_remove_training_reps_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="text",
        ),
    ]
