# Generated by Django 6.0 on 2026-01-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_remove_training_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="sets",
        ),
    ]
