# Generated by Django 6.0 on 2026-01-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_remove_training_sets"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="name",
            field=models.CharField(default="planche", max_length=200),
            preserve_default=False,
        ),
    ]
