# Generated by Django 6.0 on 2026-01-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_meal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="name",
            new_name="title",
        ),
    ]
