# Generated by Django 6.0 on 2026-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="carbs",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fats",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="protein",
            field=models.FloatField(default=0.0),
        ),
    ]
