# Generated by Django 6.0 on 2026-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_ingredient_carbs_ingredient_fats_ingredient_protein"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="kcal",
            field=models.FloatField(default=0.0),
        ),
    ]
