# Generated by Django 6.0 on 2026-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_meal_carbs_meal_fats_meal_kcal_meal_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='sets',
            field=models.IntegerField(default=0),
        ),
    ]
