# Generated by Django 6.0 on 2026-01-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_training_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_number',
            field=models.IntegerField(default=1),
        ),
    ]
