# Generated by Django 6.0 on 2026-01-19 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unit',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
