# Generated by Django 6.0 on 2026-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_unit_created_date_unit_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='unit',
            name='units',
            field=models.FloatField(default=0.0),
        ),
    ]
