# Generated by Django 6.0 on 2026-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='units',
            field=models.FloatField(default=0.1),
        ),
    ]
