# Generated by Django 6.0 on 2026-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_alter_unit_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
