# Generated by Django 6.0 on 2026-02-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_alter_set_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
