# Generated by Django 6.0 on 2026-02-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
