# Generated by Django 6.0 on 2026-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_ingredient_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
