# Generated by Django 6.0 on 2026-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_meal_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='fiber',
            field=models.FloatField(default=0.0),
        ),
    ]
