# Generated by Django 6.0 on 2026-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_unit_fiber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fiber',
            field=models.FloatField(default=0.0),
        ),
    ]
