# Generated by Django 6.0 on 2026-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_meal_fiber'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='sodium',
            field=models.FloatField(default=0.0),
        ),
    ]
