# Generated by Django 6.0 on 2026-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_ingredient_sodium'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='sodium',
            field=models.FloatField(default=0.0),
        ),
    ]
